version: "3.9"

services:
  api:
    build: ./api
    container_name: legal_api
    ports:
      - "8000:8000"
    volumes:
      - ./uploads:/app/public/uploads
    environment:
      RAILS_ENV: development
      DATABASE_HOST: api-db
      DATABASE_NAME: development
      DATABASE_USER: user
      DATABASE_PASSWORD: password
      RAG_URL: http://host.docker.internal:8001
      LLM_URL: http://host.docker.internal:8002
    command: bash -c "rm -f /app/tmp/pids/server.pid && bundle exec rails db:prepare && bundle exec rails server -b 0.0.0.0 -p 8000"

    depends_on:
      - api-db
      - llm
      - rag
      - n8n
    restart: unless-stopped

  api-db:
    image: postgres:17
    container_name: legal_api_db
    volumes:
      - postgres_db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    restart: unless-stopped

  llm:
    build: ./llm
    container_name: legal_llm
    ports:
      - "8002:8002"
    environment:
      DMR_BASE_URL: http://model-runner.docker.internal:12434/v1
      DMR_MODEL: hf.co/Qwen/Qwen2.5-7B-Instruct-GGUF:Q4_K_M
      DMR_TIMEOUT_SECONDS: 120
    extra_hosts:
      - "model-runner.docker.internal:host-gateway"
    restart: unless-stopped

  n8n:
    image: n8nio/n8n:latest
    container_name: legal_n8n

    env_file:
      - ./n8n/env.n8n

    ports:
      - "5678:5678"

    environment:
      N8N_SECURE_COOKIE: "false"
      N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS: "true"
      N8N_RUNNERS_ENABLED: "true"
      N8N_BLOCK_ENV_ACCESS_IN_NODE: "false"

    extra_hosts:
      - "host.docker.internal:host-gateway"

    volumes:
      - ./n8n_data:/home/node/.n8n
      - ./n8n:/files

    restart: unless-stopped

  rag:
    build: ./rag
    container_name: legal_rag
    ports:
      - "8001:8001"
    volumes:
      - ./data:/app/data
      - ./uploads:/app/uploads
    environment:
      DATABASE_HOST: api-db
      DATABASE_PORT: 5432
      DATABASE_NAME: development
      DATABASE_USER: user
      DATABASE_PASSWORD: password
    restart: unless-stopped

volumes:
  postgres_db:
  uploads:
