version: "3.9"

services:
  api:
    build: ./api
    container_name: legal_api
    ports:
      - "8000:8000"
    volumes:
      - ./uploads:/app/public/uploads
    environment:
      RAILS_ENV: development
      DATABASE_HOST: api-db
      DATABASE_USER: user
      DATABASE_PASSWORD: password
    command: >
      bash -c "
        bundle exec rails db:create &&
        bundle exec rails db:migrate &&
        bundle exec rails s -p 8000 -b 0.0.0.0
      "
    depends_on:
      - api-db
      - llm
    restart: unless-stopped

  api-db:
    image: postgres:17
    container_name: legal_api_db
    volumes:
      - postgres_db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    restart: unless-stopped

  llm:
    build: ./llm
    container_name: legal_llm
    ports:
      - "8002:8002"
    environment:
      DMR_BASE_URL: http://model-runner.docker.internal:12434/engines/v1
      # DMR_MODEL: huggingface.co/qwen/qwen3.5-4b:latest
      DMR_MODEL: docker.io/ai/qwen2.5:latest
      DMR_TIMEOUT_SECONDS: 120
    extra_hosts:
      - "model-runner.docker.internal:host-gateway"
    restart: unless-stopped

volumes:
  postgres_db:
  uploads: