source "https://rubygems.org"
gem "rails", "~> 8.0.2"
gem 'pg'
gem "puma"
gem "jbuilder"

gem "tzinfo-data", platforms: %i[ windows jruby ]
gem "solid_cache"
gem "solid_queue"
gem "solid_cable"
gem 'shrine'

gem "bootsnap", require: false
gem "kamal", require: false
gem 'ransack'

group :development, :test do
  gem "rspec-rails", "~> 7.0"
  gem "factory_bot_rails"
end